import './globals.css';
import { Geist, Geist_Mono } from 'next/font/google';

import Navbar from '../components/Navbar';
import Footer from '../components/Footer';
import Providers from '../Providers/Providers';
import { QueryProvider } from "../Providers/QueryProvider";

const geistSans = Geist({ subsets: ['latin'], variable: '--font-geist-sans' });
const geistMono = Geist_Mono({ subsets: ['latin'], variable: '--font-geist-mono' });


export const metadata = {
  title: 'IO Tech',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Providers>
          <QueryProvider>
            <div className="min-h-screen flex flex-col">
              <Navbar  />
              <div className="flex-grow">{children}</div>
              <Footer />
            </div>
          </QueryProvider>
        </Providers>
      </body>
    </html>
  );
}